name: Build MX4300

on: workflow_dispatch

jobs:
    build:
        name: Build MX4300 firmware images
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      python3-distutils \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4

            - name: Update feeds
              run:  make package/symlinks

            - name: Generate config
              run:  sh genconfig.sh

            - name: Build firmware images
              run: make -j$(($(nproc)+1)) download world

            - name: Get SHA
              uses: benjlevesque/short-sha@v2.2

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: qualcommax-${{ env.SHA }}
                artifacts: bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x-linksys_mx4300*
