name: Build MX4300 NSS

on: 
  workflow_dispatch:
    branches:
      - mx4300-nss

jobs:
    build:
        name: Build MX4300 NSS firmware images
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      python3-distutils \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4

            - name: Import config
              run: mv .config_mx4300_nss .config

            - name: Update feeds
              run: make package/symlinks

            - name: Build firmware images
              run: make -j$(($(nproc)+1)) world

            - name: Pack packages
              run:  tar cvfz bin/packages.tar.gz bin/targets/qualcommax/ipq807x/packages/

            - name: Get SHA
              uses: benjlevesque/short-sha@v2.2

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: qualcommax-nss-${{ env.SHA }}
                artifacts: bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x-*, bin/packages.tar.gz
